### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Andrew-Mackay** [Andrew-Mackay/peot#1]
- [x] Make 'from' parameter optional, calculating first date from git log as default
- [x] Make 'to' parameter optional, calculating most recent date from git log as default
- [ ] ~~Add optional parameter to specify the name of the main branch, defaulting to 'main'~~
- [x] Take name of git repository as parameter, cloning into a temporary directory to run the analysis
- [ ] ~~Show progress in a nicer way~~
- [ ] ~~Add optional parameter to specify where results are saved to~~
- [x] Take psalm version as parameter
- [x] Add help flag
- [x] Output commit used to calculate number of errors
- [x] Tidy up help flag
- [x] Make psalm config optional
- [x] Add desired frequency option, ['all', 'daily', 'monthly', 'yearly']
- [ ] ~~Support tilde in config path~~
- [ ] ~~Add silent mode flag~~
- [x] Write README
- [x] Add license 
- [ ] ~~Setup [completion](https://pub.dev/packages/completion)~~
- [x] Setup github action workflows for release and pr checking
- [ ] ~~Add social preview~~
- [x] Fix typo in -h for psalm-config
- [x] check requirements before running analysis

Example Graphs
![Peot Results for Andrew-Mackay_laravel_vue_blog_spa](https://user-images.githubusercontent.com/22844315/107846848-fe353800-6dde-11eb-9873-b43485a6e66b.png)
